version: "3"
services:
  postgres:
    image: "postgres:9.6"
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  # comment initdb if after first run
   initdb:
   build: .
   entrypoint: airflow initdb
   depends_on:
   - postgres
  webserver:
    container_name: airflow_webserver
    hostname: airflow_webserver
    build: .
    restart: always
    depends_on:
      - postgres
    volumes:
      - ../dags:/usr/local/airflow/dags
      - ./airflow_files:/usr/local/airflow_files
    ports:
      - "8080:8080"
    entrypoint: airflow webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
  scheduler:
    container_name: airflow_scheduler
    hostname: airflow_scheduler
    build: .
    restart: always
    depends_on:
      - postgres
      - webserver
    volumes:
      - ../dags:/usr/local/airflow/dags
      - ./airflow_files:/usr/local/airflow_files
    entrypoint: airflow scheduler
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-scheduler.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
  redis:
    container_name: redis
    hostname: redis
    image: redis:5.0.5
  worker_1:
    container_name: airflow_worker_1
    hostname: airflow_worker_1
    build: .
    restart: always
    depends_on:
      - postgres
    volumes:
      - ../dags:/usr/local/airflow/dags
      - ./airflow_files:/usr/local/airflow_files
    entrypoint: airflow worker -cn worker_1
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-worker.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
  worker_2:
    container_name: airflow_worker_2
    hostname: airflow_worker_2
    build: .
    restart: always
    depends_on:
      - postgres
    volumes:
      - ../dags:/usr/local/airflow/dags
      - ./airflow_files:/usr/local/airflow_files
    entrypoint: airflow worker -cn worker_2
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-worker.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
  worker_3:
    container_name: airflow_worker_3
    hostname: airflow_worker_3
    build: .
    restart: always
    depends_on:
      - postgres
    volumes:
      - ../dags:/usr/local/airflow/dags
      - ./airflow_files:/usr/local/airflow_files
    entrypoint: airflow worker -cn worker_3
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-worker.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
  flower:
    container_name: airflow_flower
    hostname: airflow_flower
    build: .
    restart: always
    depends_on:
      - postgres
    volumes:
      - ../dags:/usr/local/airflow/dags
      - ./airflow_files:/usr/local/airflow_files
    entrypoint: airflow flower
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-flower.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - "5555:5555"